source('~/Desktop/Simulator manuscript/SimBreeder/R/create_map.R')
source('~/Desktop/Simulator manuscript/SimBreeder/R/create_parents.R')
source('~/Desktop/Simulator manuscript/SimBreeder/R/calc_TGV.R')
source('~/Desktop/Simulator manuscript/SimBreeder/R/sim_phenos.R')
gmap <- create_genetic_map(num.chromos = 12,map.length = 1800,num.markers = 120,total.qtl = 2640,num.snpqtl = 1960,distribute.loci = "even",marker.distribution = "equally-spaced",snp.qtl.maf = c(0.01,0.02))
parents <- create_parents(map.info = gmap,num.parents = 280,max.delt.allele = 14,par.markers.unique = T,heterozygous.markers = T)
parents.TGV <- calc_TGV(geno.info = parents,map.info = gmap,A = 1,a = -100,dom.coeff = 1,founder = T)
parents.phenos <- sim_phenos(TGV.object = parents.TGV,h2 = .3)
founder.h2 <- var(parents.phenos$genetic.values)/var(parents.phenos$phenos)
E.sd <- sqrt((var(parents.phenos$genetic.values)/founder.h2) - var(parents.phenos$genetic.values))
